apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
  namespace: prod
data:
  DB_URL: "jdbc:mysql://doktori-staging-mysql.cvqsyou66939.ap-northeast-2.rds.amazonaws.com:3306/doktoridb?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_URL: "jdbc:mysql://doktori-staging-mysql.cvqsyou66939.ap-northeast-2.rds.amazonaws.com:3306/doktoridb?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true"