apiVersion: v1
kind: Service
metadata:
  name: chat-svc
  namespace: prod
  labels:
    app: doktori
    component: chat
spec:
  type: ClusterIP
  selector:
    app: doktori
    component: chat
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP