apiVersion: v1
kind: Service
metadata:
  name: chat-svc
  namespace: prod
spec:
  selector:
    app: doktori
    component: chat
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chat-pdb
  namespace: prod
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: doktori
      component: chat