{
 "title": "DB 무중단 마이그레이션 관제",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "복제 지연 시간 (초)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mysql_slave_status_seconds_behind_master\n",
     "legendFormat": "복제 지연 시간"
    }
   ]
  },
  {
   "title": "SQL 복제 Thread 상태",
   "type": "stat",
   "description": "슬레이브 DB에서 복제된 데이터를 실제로 적용하는 SQL 스레드의 동작 상태를 표시합니다.\n\n값 의미:\n- 정상 동작(1): 마스터에서 전달된 데이터를 정상적으로 적용 중\n- 중지됨(0): 복제 적용이 멈춘 상태\n\n운영 의미:\n이 값이 0이 되면 데이터 복제가 멈춘 상태이므로\n마이그레이션 컷오버(전환)를 진행하면 안 됩니다.\n\n컷오버 가능 조건\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO 복제 스레드 상태",
   "type": "stat",
   "description": "마스터 DB로부터 복제 로그(binlog)를 수신하는 IO 스레드 상태를 표시합니다.\n\n값 의미:\n- 정상 동작(1): 마스터에서 로그를 정상적으로 수신 중\n- 중지됨(0): 로그 수신이 멈춘 상태\n\n운영 의미:\nIO 스레드가 멈추면 복제 자체가 중단됩니다.\n컷오버 전에 반드시 정상 상태를 유지해야 합니다.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "복제 에러 코드",
   "type": "stat",
   "description": "복제 과정에서 발생한 마지막 에러 코드를 표시합니다.\n\n값 의미:\n0 → 정상\n0이 아닌 값 → 복제 오류 발생\n\n운영 의미:\n복제 지연 또는 중단 발생 시 원인 분석에 사용됩니다.\n컷오버 전에 반드시 0 상태를 유지해야 합니다.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_last_errno\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\nsort @timestamp desc |\nlimit 20",
     "logGroups": [
      {
       "accountId": "246477585940",
       "arn": "arn:aws:logs:ap-northeast-2:246477585940:log-group:/aws/rds/instance/database-migration/error:*",
       "name": "/aws/rds/instance/database-migration/error"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "ap-northeast-2",
     "statistic": "Average"
    }
   ]
  }
 ]
}