#!/usr/bin/env bash
# =============================================================================
# Auto-generated K8s inventory cleanup
#
# Usage: ./clear-inventory.sh
# Removes only inventory/k8s-hosts.yml generated by generate-inventory.sh.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INVENTORY_FILE="${SCRIPT_DIR}/inventory/k8s-hosts.yml"

if [ ! -e "$INVENTORY_FILE" ]; then
  echo "삭제할 K8s inventory가 없습니다: ${INVENTORY_FILE}"
  exit 0
fi

rm -f "$INVENTORY_FILE"

echo "K8s inventory 삭제 완료: ${INVENTORY_FILE}"
