#!/usr/bin/env bash
# =============================================================================
# AWS 태그 기반 K8s inventory 자동 생성
# ASG 인스턴스의 Name 태그 + Role 태그로 master/worker 분류
#
# Usage: ./generate-inventory.sh
# Output: inventory/k8s-hosts.yml
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT="${SCRIPT_DIR}/inventory/k8s-hosts.yml"

mkdir -p "$(dirname "$OUTPUT")"

echo "K8s inventory 생성 중..."

# Master 인스턴스
MASTERS=$(aws ec2 describe-instances \
  --filters \
    "Name=tag:Role,Values=k8s-cp" \
    "Name=instance-state-name,Values=running" \
  --query 'Reservations[].Instances[].[InstanceId,PrivateIpAddress]' \
  --output text)

# Worker 인스턴스
WORKERS=$(aws ec2 describe-instances \
  --filters \
    "Name=tag:Role,Values=k8s-worker" \
    "Name=instance-state-name,Values=running" \
  --query 'Reservations[].Instances[].[InstanceId,PrivateIpAddress]' \
  --output text)

cat > "$OUTPUT" <<'HEADER'
# Auto-generated by generate-inventory.sh
# Re-run after ASG scaling or instance replacement
all:
  vars:
    ansible_user: ubuntu
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_region: ap-northeast-2
    ansible_python_interpreter: /usr/bin/python3
  children:
    k8s_master:
      hosts:
HEADER

# Master 호스트 추가
FIRST_MASTER=true
while IFS=$'\t' read -r instance_id private_ip; do
  [ -z "$instance_id" ] && continue
  echo "        ${instance_id}:" >> "$OUTPUT"
  echo "          ansible_aws_ssm_instance_id: ${instance_id}" >> "$OUTPUT"
  echo "          private_ip: ${private_ip}" >> "$OUTPUT"
  if [ "$FIRST_MASTER" = true ]; then
    echo "          primary_master: true" >> "$OUTPUT"
    FIRST_MASTER=false
  fi
done <<< "$MASTERS"

cat >> "$OUTPUT" <<'WORKERS_HEADER'
    k8s_workers:
      hosts:
WORKERS_HEADER

# Worker 호스트 추가
while IFS=$'\t' read -r instance_id private_ip; do
  [ -z "$instance_id" ] && continue
  echo "        ${instance_id}:" >> "$OUTPUT"
  echo "          ansible_aws_ssm_instance_id: ${instance_id}" >> "$OUTPUT"
  echo "          private_ip: ${private_ip}" >> "$OUTPUT"
done <<< "$WORKERS"

cat >> "$OUTPUT" <<'FOOTER'
    k8s_all:
      children:
        k8s_master:
        k8s_workers:
FOOTER

echo ""
echo "inventory 생성 완료: ${OUTPUT}"
echo ""
echo "--- Masters ---"
echo "$MASTERS" | while IFS=$'\t' read -r id ip; do echo "  ${id} (${ip})"; done
echo ""
echo "--- Workers ---"
echo "$WORKERS" | while IFS=$'\t' read -r id ip; do echo "  ${id} (${ip})"; done
